# Generated by Django 2.0.1 on 2018-03-17 15:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0002_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('KB', 'Children'), ('EL', 'Elderly'), ('HO', 'Homeless'), ('TE', 'Tech'), ('MU', 'Music'), ('EV', 'Environmental'), ('ED', 'Educational')], default=None, max_length=14),
        ),
    ]
