# Generated by Django 2.0.1 on 2018-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0003_volunteer_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='adress',
            field=models.TextField(default=997),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.TextField(default='dupex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='duration',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='phone_number',
            field=models.CharField(default='997', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(default=997, max_length=15),
            preserve_default=False,
        ),
    ]
