# Generated by Django 2.0.1 on 2018-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0004_auto_20180317_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(default='AA', max_length=2),
            preserve_default=False,
        ),
    ]
