# Generated by Django 2.0 on 2018-03-18 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hex', '0005_events_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hex.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AE', 'Arts and Entertainment'), ('BZ', 'Business'), ('BP', 'Biological and Physical Sciences'), ('ED', 'Education'), ('EV', 'Environment'), ('GV', 'Government'), ('HM', 'Health &amp; Medicine'), ('IT', 'International'), ('LP', 'Law and Public Policy'), ('NP', 'Nonprofit'), ('SO', 'Society'), ('TC', 'Technology')], default=None, max_length=24),
        ),
    ]
