# Generated by Django 2.0 on 2018-03-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hex', '0006_auto_20180318_0205'),
        ('hex', '0006_auto_20180318_0156'),
    ]

    operations = [
    ]
